defaults: &defaults
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *defaults
  database: pluck_development

test:
  <<: *defaults
  database: pluck_test

production:
  <<: *defaults
  database: pluck_production